
const LOGIN = "LOGIN"
const LOGIN_SUCCESS = "LOGIN_SUCCESS"
const LOGIN_FAILURE = "LOGIN_FAILURE"

//logout 
export const LOGOUT = 'LOGOUT'


//Register
const SIGNUP = "SIGNUP"
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
const SIGNUP_FAILURE = "SIGNUP_FAILURE"

const GET_DOCTOR_PROFILE = "GET_DOCTOR_PROFILE"
const GET_DOCTOR_PROFILE_SUCCESS = "GET_DOCTOR_PROFILE_SUCCESS"
const GET_DOCTOR_PROFILE_FAILURE = "GET_DOCTOR_PROFILE_FAILURE"

const UPDATE_DOCTOR_PROFILE = "UPDATE_DOCTOR_PROFILE"
const UPDATE_DOCTOR_PROFILE_SUCCESS = "UPDATE_DOCTOR_PROFILE_SUCCESS"
const UPDATE_DOCTOR_PROFILE_FAILURE = "UPDATE_DOCTOR_PROFILE_FAILURE"

const GET_HEALTH = "GET_HEALTH"
const GET_HEALTH_SUCCESS = "GET_HEALTH_SUCCESS"
const GET_HEALTH_FAILURE = "GET_HEALTH_FAILURE"


const GET_PATIENTS = "GET_PATIENTS"
const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS"
const GET_PATIENTS_FAILURE = "GET_PATIENTS_FAILURE"

const GET_PATIENT_DETAIL = "GET_PATIENT_DETAIL"
const GET_PATIENT_DETAIL_SUCCESS = "GET_PATIENT_DETAIL_SUCCESS"
const GET_PATIENT_DETAIL_FAILURE = "GET_PATIENT_DETAIL_FAILURE"

const SET_PATIENT_PERSONAL_INFO = "SET_PATIENT_PERSONAL_INFO"
const SET_PATIENT_PERSONAL_INFO_SUCCESS = "SET_PATIENT_PERSONAL_INFO_SUCCESS"
const SET_PATIENT_PERSONAL_INFO_FAILURE = "SET_PATIENT_PERSONAL_INFO_FAILURE"


const SET_PATIENT_HEALTH_INFO = "SET_PATIENT_HEALTH_INFO"
const SET_PATIENT_HEALTH_INFO_SUCCESS = "SET_PATIENT_HEALTH_INFO_SUCCESS"
const SET_PATIENT_HEALTH_INFO_FAILURE = "SET_PATIENT_HEALTH_INFO_FAILURE"
const CLEAR_PATIENT_HEALTH_INFO = "CLEAR_PATIENT_HEALTH_INFO"

const GET_PATIENT_HEALTH_INFO = "GET_PATIENT_HEALTH_INFO"
const GET_PATIENT_HEALTH_INFO_SUCCESS = "GET_PATIENT_HEALTH_INFO_SUCCESS"
const GET_PATIENT_HEALTH_INFO_FAILURE = "GET_PATIENT_HEALTH_INFO_FAILURE"

const GET_PATIENT_HEALTH_RECORD = "GET_PATIENT_HEALTH_RECORD"
const GET_PATIENT_HEALTH_RECORD_SUCCESS = "GET_PATIENT_HEALTH_RECORD_SUCCESS"
const GET_PATIENT_HEALTH_RECORD_FAILURE = "GET_PATIENT_HEALTH_RECORD_FAILURE"

const UPLOAD_PATIENT_HISTORY = "UPLOAD_PATIENT_HISTORY"
const UPLOAD_PATIENT_HISTORY_SUCCESS = "UPLOAD_PATIENT_HISTORY_SUCCESS"
const UPLOAD_PATIENT_HISTORY_FAILURE = "UPLOAD_PATIENT_HISTORY_FAILURE"

const ADD_PATIENT_HISTORY = "ADD_PATIENT_HISTORY"
const ADD_PATIENT_HISTORY_SUCCESS = "ADD_PATIENT_HISTORY_SUCCESS"
const ADD_PATIENT_HISTORY_FAILURE = "ADD_PATIENT_HISTORY_FAILURE"


const GET_HISTORY = "GET_HISTORY"
const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS"
const GET_HISTORY_FAILURE = "GET_HISTORY_FAILURE"

export {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,

    SIGNUP,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,

    GET_DOCTOR_PROFILE,
    GET_DOCTOR_PROFILE_SUCCESS,
    GET_DOCTOR_PROFILE_FAILURE,

    UPDATE_DOCTOR_PROFILE,
    UPDATE_DOCTOR_PROFILE_SUCCESS,
    UPDATE_DOCTOR_PROFILE_FAILURE,

    GET_HEALTH,
    GET_HEALTH_SUCCESS,
    GET_HEALTH_FAILURE,

    GET_PATIENTS,
    GET_PATIENTS_SUCCESS,
    GET_PATIENTS_FAILURE,

    GET_PATIENT_DETAIL,
    GET_PATIENT_DETAIL_SUCCESS,
    GET_PATIENT_DETAIL_FAILURE,

    SET_PATIENT_PERSONAL_INFO,
    SET_PATIENT_PERSONAL_INFO_SUCCESS,
    SET_PATIENT_PERSONAL_INFO_FAILURE,

    SET_PATIENT_HEALTH_INFO,
    SET_PATIENT_HEALTH_INFO_SUCCESS,
    SET_PATIENT_HEALTH_INFO_FAILURE,
    CLEAR_PATIENT_HEALTH_INFO,

    GET_PATIENT_HEALTH_INFO,
    GET_PATIENT_HEALTH_INFO_SUCCESS,
    GET_PATIENT_HEALTH_INFO_FAILURE,

    GET_PATIENT_HEALTH_RECORD,
    GET_PATIENT_HEALTH_RECORD_SUCCESS,
    GET_PATIENT_HEALTH_RECORD_FAILURE,

    UPLOAD_PATIENT_HISTORY,
    UPLOAD_PATIENT_HISTORY_SUCCESS,
    UPLOAD_PATIENT_HISTORY_FAILURE,

    ADD_PATIENT_HISTORY,
    ADD_PATIENT_HISTORY_SUCCESS,
    ADD_PATIENT_HISTORY_FAILURE,

    GET_HISTORY,
    GET_HISTORY_SUCCESS,
    GET_HISTORY_FAILURE
}

export const actionsTypes = {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,

    SIGNUP,
    SIGNUP_SUCCESS,
    SIGNUP_FAILURE,

    GET_DOCTOR_PROFILE,
    GET_DOCTOR_PROFILE_SUCCESS,
    GET_DOCTOR_PROFILE_FAILURE,

    UPDATE_DOCTOR_PROFILE,
    UPDATE_DOCTOR_PROFILE_SUCCESS,
    UPDATE_DOCTOR_PROFILE_FAILURE,

    GET_HEALTH,
    GET_HEALTH_SUCCESS,
    GET_HEALTH_FAILURE,

    GET_PATIENTS,
    GET_PATIENTS_SUCCESS,
    GET_PATIENTS_FAILURE,

    GET_PATIENT_DETAIL,
    GET_PATIENT_DETAIL_SUCCESS,
    GET_PATIENT_DETAIL_FAILURE,


    SET_PATIENT_PERSONAL_INFO,
    SET_PATIENT_PERSONAL_INFO_SUCCESS,
    SET_PATIENT_PERSONAL_INFO_FAILURE,
    CLEAR_PATIENT_HEALTH_INFO,

    GET_PATIENT_HEALTH_INFO,
    GET_PATIENT_HEALTH_INFO_SUCCESS,
    GET_PATIENT_HEALTH_INFO_FAILURE,

    SET_PATIENT_HEALTH_INFO,
    SET_PATIENT_HEALTH_INFO_SUCCESS,
    SET_PATIENT_HEALTH_INFO_FAILURE,

    GET_PATIENT_HEALTH_RECORD,
    GET_PATIENT_HEALTH_RECORD_SUCCESS,
    GET_PATIENT_HEALTH_RECORD_FAILURE,

    UPLOAD_PATIENT_HISTORY,
    UPLOAD_PATIENT_HISTORY_SUCCESS,
    UPLOAD_PATIENT_HISTORY_FAILURE,

    ADD_PATIENT_HISTORY,
    ADD_PATIENT_HISTORY_SUCCESS,
    ADD_PATIENT_HISTORY_FAILURE,

    GET_HISTORY,
    GET_HISTORY_SUCCESS,
    GET_HISTORY_FAILURE,

}